### PR TITLE
Feature/improvingsimplepir

### PR DESCRIPTION
**Pull request by carlosaguilarmelchor**
simplePIR : 
- commented example to do multiple reply generations
- better output for the tests
- better error checking for dbdirectoryprocessor

General: 
- some leaks fixed
- mkdb-correctness does not rebuild the database if check.repo exists
- added error status to dbdirectoryprocessor

### CODE REVIEW

**Comment by carlosaguilarmelchor** [comment]
New commits

Improved replyGenerator :
- won't use dbhandler when not supposed to
- better memory cleanup system
- better initialization of critical variables (reply generation reusable now for the same object)

simplepir : 
- more details on the advanced example
- no more need to call setpirparams after the construction
- replygeneration function adapted to be reusable

**Comment by Kirija** [comment]
Wow, this looks good. Maybe a 0.2.1 candidate 👍 
I have to properly check it and I'll comment on PR

**Comment by carlosaguilarmelchor** [comment]
Removed all leaks (except minor leaks coming from openmp threads that do not join) on simplePIR.

@Kirija I restored all the tests on simplePIR a bug persists wait until I solve it to merge please

**Comment by carlosaguilarmelchor** [comment]
Hmmm a big leak remains when we use recursion. Please wait until I solve it before merging.

**Comment by carlosaguilarmelchor** [comment]
@Kirija  pushed bugfix for recursion merge is ok for me now

**Comment by carlosaguilarmelchor** [comment]
@Kirija ok for a new release v0.2.1 :) 
We will do v0.2.2 when compilation and execution issues on OSX will be solved.

**Pull request merged**
